// Shared data — specialty icons are handled in components via lucide-react

export const SPECIALTY_META = {
  nursing: {
    label: 'Home Nursing',
    color: '#1D4ED8',
    bg: '#EFF6FF',
    iconName: 'stethoscope',
  },
  babysitting: {
    label: 'Babysitting & Childcare',
    color: '#6D28D9',
    bg: '#F5F3FF',
    iconName: 'baby',
  },
  cleaning: {
    label: 'Indoor Cleaning',
    color: '#059669',
    bg: '#ECFDF5',
    iconName: 'sparkles',
  },
  outdoor_cleaning: {
    label: 'Outdoor Cleaning',
    color: '#0284C7',
    bg: '#F0F9FF',
    iconName: 'droplets',
  },
  gardening: {
    label: 'Gardening & Lawn Care',
    color: '#15803D',
    bg: '#F0FDF4',
    iconName: 'leaf',
  },
  pet_care: {
    label: 'Pet Care & Walking',
    color: '#D97706',
    bg: '#FFFBEB',
    iconName: 'heart',
  },
  elderly_care: {
    label: 'Elderly Care',
    color: '#BE185D',
    bg: '#FDF2F8',
    iconName: 'user-check',
  },
  laundry_ironing: {
    label: 'Laundry & Ironing',
    color: '#4F46E5',
    bg: '#EEF2FF',
    iconName: 'shirt',
  },
  cooking: {
    label: 'Cooking & Meal Prep',
    color: '#EA580C',
    bg: '#FFF7ED',
    iconName: 'utensils',
  },
}

export const CAREGIVERS = [
  {
    id: '1',
    name: 'Marie-Claire Nkomo',
    specialty: 'nursing',
    rating: 4.9,
    reviewCount: 47,
    pricePerHour: 3500,
    location: 'Bastos, Yaounde',
    photo: 'https://images.unsplash.com/photo-1627328543975-3f0ba8a823b0?w=400&h=400&fit=crop&auto=format',
    bio: "Certified nurse with 8 years of experience in home care for elderly and post-operative patients. Specialized in post-surgical care and chronic disease management. Fluent in French and English, adapting to each family's specific needs with care and professionalism.",
    certifications: ['ID Verified', 'State Nursing Diploma', 'First Aid Certified', 'Palliative Care', 'References Checked'],
    available: true,
    languages: ['French', 'English', 'Bassa'],
    responseTime: '< 2h',
    experience: 8,
    serviceArea: 'Yaounde — 10 km radius',
    reviews: [
      { author: 'Njoya Family', rating: 5, date: 'June 2025', comment: 'Marie-Claire cared for my mother with extraordinary patience and gentleness. I recommend her without hesitation. She is punctual, professional, and truly humane.' },
      { author: 'Bernadette K.', rating: 5, date: 'May 2025', comment: "Excellent nurse. She reassured our family during my father's recovery after surgery. Very competent." },
      { author: 'Rodrigue M.', rating: 4, date: 'April 2025', comment: 'Very professional and available. Communication is clear and she explains every procedure. Slightly late on the first appointment but nothing serious.' },
    ],
  },
  {
    id: '2',
    name: 'Fatima Bello',
    specialty: 'babysitting',
    rating: 4.8,
    reviewCount: 63,
    pricePerHour: 2800,
    location: 'Akwa, Douala',
    photo: 'https://images.unsplash.com/photo-1579255565889-2ac16e9b2950?w=400&h=400&fit=crop&auto=format',
    bio: 'Certified early childhood educator with 5 years of experience. I care for children aged 6 months to 10 years with age-appropriate educational activities — reading, creative games, motor activities. Bilingual, creating a safe and stimulating environment for every child.',
    certifications: ['ID Verified', 'Certified Educator', 'Pediatric First Aid', 'References Checked'],
    available: true,
    languages: ['French', 'English', 'Hausa'],
    responseTime: '< 1h',
    experience: 5,
    serviceArea: 'Douala — 8 km radius',
    reviews: [
      { author: 'Sophie & David A.', rating: 5, date: 'July 2025', comment: 'Fatima is fantastic with our two children (3 and 6 years old). Creative, patient, and always on time. Our kids love her!' },
      { author: 'Carole N.', rating: 5, date: 'June 2025', comment: 'Very reassuring with my 8-month-old baby. She communicates well and sends photos regularly.' },
    ],
  },
  {
    id: '3',
    name: 'Elise Fouda',
    specialty: 'cleaning',
    rating: 4.7,
    reviewCount: 89,
    pricePerHour: 2200,
    location: 'Omnisports, Yaounde',
    photo: 'https://images.unsplash.com/photo-1677195063105-276fd4b95b21?w=400&h=400&fit=crop&auto=format',
    bio: 'Expert housekeeper with over 6 years of experience. Meticulous and discreet, bringing eco-friendly products. Full cleaning, ironing, and organization. Available for one-off sessions or regular schedules.',
    certifications: ['ID Verified', 'References Checked (12 families)'],
    available: true,
    languages: ['French', 'Ewondo'],
    responseTime: '< 3h',
    experience: 6,
    serviceArea: 'Yaounde — 15 km radius',
    reviews: [
      { author: 'Isabelle T.', rating: 5, date: 'July 2025', comment: 'My house has never been this clean! Elise is methodical, discreet, and honest. Client for 8 months.' },
      { author: 'Marc-Antoine B.', rating: 4, date: 'May 2025', comment: 'Great work, quality eco-friendly products. Punctual and efficient.' },
    ],
  },
  {
    id: '4',
    name: 'Paul Mbarga',
    specialty: 'nursing',
    rating: 4.6,
    reviewCount: 31,
    pricePerHour: 3200,
    location: 'Bonanjo, Douala',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&auto=format',
    bio: 'Certified nurse specialized in geriatrics and home care. 6 years supporting elderly patients and those in rehabilitation. Empathetic and rigorous, supporting both patients and their families.',
    certifications: ['ID Verified', 'State Nursing Diploma', 'Geriatrics Certified', 'First Aid Certified'],
    available: false,
    languages: ['French', 'English', 'Beti'],
    responseTime: '< 4h',
    experience: 6,
    serviceArea: 'Douala — 12 km radius',
    reviews: [
      { author: 'Essomba Family', rating: 5, date: 'June 2025', comment: 'Paul accompanied our father during recovery with great humanity. He explains every procedure and reassures the family.' },
    ],
  },
  {
    id: '5',
    name: 'Samuel Eto’o Nkodo',
    specialty: 'gardening',
    rating: 4.9,
    reviewCount: 42,
    pricePerHour: 2500,
    location: 'Mvan, Yaounde',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&auto=format',
    bio: 'Professional gardener and landscaper with 7 years of experience. Specializing in lawn grooming, hedge trimming, flower planting, and organic garden maintenance across Yaounde.',
    certifications: ['ID Verified', 'Horticulture Certificate', 'References Checked'],
    available: true,
    languages: ['French', 'English'],
    responseTime: '< 1h',
    experience: 7,
    serviceArea: 'Yaounde — 15 km radius',
    reviews: [
      { author: 'Abena Pierre', rating: 5, date: 'August 2025', comment: 'Transformed our front yard completely! Very reliable and neat.' },
    ],
  },
  {
    id: '6',
    name: 'Nathalie Eyenga',
    specialty: 'pet_care',
    rating: 4.8,
    reviewCount: 38,
    pricePerHour: 2000,
    location: 'Bonamoussadi, Douala',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&auto=format',
    bio: 'Passionate animal caregiver with 4+ years of veterinary assistant experience. Specializing in dog walking, feeding routines, medication administration, and loving companionship while families travel.',
    certifications: ['ID Verified', 'Vet Assistant Diploma', 'Pet First Aid'],
    available: true,
    languages: ['French', 'English'],
    responseTime: '< 2h',
    experience: 4,
    serviceArea: 'Douala — 10 km radius',
    reviews: [
      { author: 'Chantal M.', rating: 5, date: 'July 2025', comment: 'Our two dogs adore Nathalie. She sends updates with photos during every visit.' },
    ],
  },
  {
    id: '7',
    name: 'Chef Brigitte Manga',
    specialty: 'cooking',
    rating: 4.9,
    reviewCount: 56,
    pricePerHour: 3000,
    location: 'Bonapriso, Douala',
    photo: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&h=400&fit=crop&auto=format',
    bio: 'Professional home chef and dietary nutritionist with 9 years of culinary experience. Specializing in Cameroonian traditional meals, healthy diabetic/low-sodium diets, and weekly family meal prepping.',
    certifications: ['ID Verified', 'Culinary Arts Diploma', 'Hygiene & Food Safety'],
    available: true,
    languages: ['French', 'English', 'Duala'],
    responseTime: '< 1h',
    experience: 9,
    serviceArea: 'Douala — 15 km radius',
    reviews: [
      { author: 'Kouam Family', rating: 5, date: 'August 2025', comment: 'Brigitte cooks the most exquisite and healthy family meals. Highly recommended!' },
    ],
  },
]
